apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: aws-ec2-instance
  title: AWS EC2 Instance Provisioning
  description: Template for provisioning an EC2 instance in the AWS cloud
  tags: ['aws']
spec:
  owner: guests
  type: service
  parameters:
    # Parameters for EC2 instance creation
    - title: EC2 Instance Creation
      required:
         - InstanceName
         - Region
         - InstanceType    
      properties:
        InstanceName:
          title: Instance Name.
          type: string
          description: Enter a name for the EC2 instance
          ui:autofocus: true
          ui:options:
            rows: 5

        Region:
          title:  AWS Region
          type: string
          description: Select the region where you want to create the EC2 instance
          enum:
            - us-west-1
            - us-west-2
            - us-east-1
            - us-east-2

        InstanceType:
          title: Type of Instance.
          type: string
          description: Select the instance type for the EC2 instance
          enum:
            - t2.medium
            - t2.small
            - t2.micro
            - t3.medium
        action:
          title: action
          type: string
          description: Specify whether to create or delete the EC2 instance
          enum:
            - apply
            - destroy

    # Parameter for choosing a repository location
    - title: Choose a Repository Location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository URL
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    # Step 1: Fetch details from content folder
    - id: fetch-base
      name: Fetching Details from content folder
      action: fetch:template
      input:
        url: ./content
        values:
          name: ${{ parameters.InstanceName}}

    # Step 2: Publish details to GitHub repository
    - id: publish
      name: Publishing Details
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: Repository to create an EC2 instance named ${{ parameters.InstanceName }} using Backstage.
        repoUrl: ${{ parameters.repoUrl }}
        repoVisibility: public

    # Step 3: Trigger GitHub Actions
    - id: github-action
      name: Starting GitHub Action
      action: github:actions:dispatch
      input:
        workflowId:  ec2instance.yml # ID of GitHub action WorkFlow
        repoUrl: 'github.com?repo=aws-ec2&owner=kanupriya0508'
        branchOrTagName: 'main'
        workflowInputs:
          instance_name: ${{ parameters.InstanceName }}
          aws_region: ${{ parameters.Region }}
          instance_type: ${{ parameters.InstanceType }}
          action: ${{ parameters.action }}

    # Step 4: Register the new component in the Backstage catalog
    - id: register
      name: Registering the New Component 
      action: catalog:register
      input:
        repoContentsUrl: ${{steps['publish'].output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'

  # Output links displayed to the user after the template execution
  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps['register'].output.entityRef }}